# Generated by Django 3.1.5 on 2021-01-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('body_style', models.CharField(max_length=200)),
            ],
        ),
    ]
